import {Sarabun} from "next/font/google";
import "./globals.css";
import {Sidebar} from "@/components/sidebar";
import {Navbar} from "@/components/navbar";

export const sarabun = Sarabun({
    subsets: ['thai'],
    display: 'swap',
    weight: "500",
    style: "normal"
})
export const metadata = {
    title: "Ozoneaik Website",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={sarabun.className}>
        <Navbar/>
        <div className={'content'}>
            {children}
        </div>
        </body>
        </html>
    );
}
